# -*- coding: utf-8 -*-
"""Whether-Report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VGvoiwxxGNmpcMP-_Yn_W26ChK84T-2Q
"""



import requests

API_KEY = "4d7f263908ac1c04574dc6eb9ee095be"   # Replace with your API key
BASE_URL = "https://api.openweathermap.org/data/2.5/weather"

city = input("Enter city name: ")

params = {
    "q": city,
    "appid": API_KEY,
    "units": "metric"   # or 'imperial' for Fahrenheit
}

response = requests.get(BASE_URL, params=params)

if response.status_code == 200:
    data = response.json()
    main = data['main']
    weather = data['weather'][0]

    print(f"\nWeather in {city}:")
    print(f"Temperature: {main['temp']}°C")
    print(f"Feels Like: {main['feels_like']}°C")
    print(f"Humidity: {main['humidity']}%")
    print(f"Condition: {weather['description'].title()}")
else:
    # Improved error handling to show API's specific message
    try:
        error_data = response.json()
        print(f"API Error for {city}: {error_data.get('message', 'Unknown API error')}")
    except requests.exceptions.JSONDecodeError:
        print(f"API Error: Could not decode JSON response from API. Status code: {response.status_code}")
    print(f"Status Code: {response.status_code}")